/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate a user using their email address and password. Returns JWT access and refresh tokens.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Blacklist the supplied refresh token so it cannot be used to obtain new access tokens.
         */
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current User
         * @description Retrieve details of the currently authenticated user.
         */
        get: operations["auth_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Access Token
         * @description Generate a new access token using a valid refresh token. Refresh tokens are rotated: the response includes a new refresh token and the submitted one is blacklisted.
         */
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description Return all active members available for lead assignment.
         */
        get: operations["auth_users_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List visible leads
         * @description Returns a paginated list of leads visible to the authenticated user. Supports search, filtering and ordering.
         */
        get: operations["leads_list"];
        put?: never;
        /**
         * Create a lead
         * @description Create a new lead. The lead is automatically created with status NEW and is initially unassigned.
         */
        post: operations["leads_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Retrieve a lead
         * @description Retrieve a single lead that is visible to the authenticated user.
         */
        get: operations["leads_retrieve"];
        /**
         * Update a lead
         * @description Update lead information. Status changes and assignment are handled through dedicated endpoints.
         */
        put: operations["leads_update"];
        post?: never;
        /**
         * Delete a lead
         * @description Permanently delete a lead visible to the authenticated user.
         */
        delete: operations["leads_destroy"];
        options?: never;
        head?: never;
        /**
         * Update a lead
         * @description Update lead information. Status changes and assignment are handled through dedicated endpoints.
         */
        patch: operations["leads_partial_update"];
        trace?: never;
    };
    "/api/leads/{id}/activities/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List lead activities
         * @description Retrieve activities recorded for a lead visible to the authenticated user.
         */
        get: operations["leads_activities_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads/{id}/assign/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign a lead
         * @description Assign a lead to an active member. Administrator access is required.
         */
        post: operations["leads_assign_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads/{id}/notes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a lead note
         * @description Create a note for a lead and record the related activity.
         */
        post: operations["leads_notes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads/{id}/notes/list/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List lead notes
         * @description Retrieve all notes for a lead visible to the authenticated user.
         */
        get: operations["leads_notes_list_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads/{id}/status/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change a lead's status
         * @description Change a lead's status when the requested transition is allowed.
         */
        post: operations["leads_status_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leads/notes/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Provide update and delete operations for lead notes. */
        put: operations["leads_notes_update"];
        post?: never;
        /**
         * Delete a lead note
         * @description Permanently delete a lead note the authenticated user may manage.
         */
        delete: operations["deleteLeadNote"];
        options?: never;
        head?: never;
        /**
         * Update a lead note
         * @description Update the content of a lead note.
         */
        patch: operations["updateLeadNote"];
        trace?: never;
    };
    "/api/leads/public/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a public lead
         * @description Create a new lead without authentication.
         */
        post: operations["leads_public_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `CREATED` - Created
         *     * `STATUS_CHANGED` - Status Changed
         *     * `ASSIGNED` - Assigned
         *     * `NOTE_ADDED` - Note Added
         *     * `UPDATED` - Updated
         * @enum {string}
         */
        ActivityTypeEnum: "CREATED" | "STATUS_CHANGED" | "ASSIGNED" | "NOTE_ADDED" | "UPDATED";
        /** @description Validate the member selected to receive a lead assignment. */
        AssignLeadRequest: {
            /** @description ID of the user to assign the lead to. */
            assigned_to: number;
        };
        /** @description Validate a requested lead status change. */
        ChangeLeadStatusRequest: {
            /**
             * @description New status for the lead.
             *
             *     * `NEW` - New
             *     * `CONTACTED` - Contacted
             *     * `QUALIFIED` - Qualified
             *     * `PROPOSAL` - Proposal
             *     * `WON` - Won
             *     * `LOST` - Lost
             */
            status: components["schemas"]["StatusEnum"];
        };
        /** @description Serialize standard API error details. */
        Error: {
            /** @description Error description. */
            detail: string;
        };
        /** @description Serialize lead details for retrieval. */
        Lead: {
            readonly id: number;
            first_name: string;
            last_name: string;
            /** Format: email */
            email: string;
            phone?: string;
            company?: string;
            source?: string;
            readonly status: components["schemas"]["StatusEnum"];
            /** @description The user who created the lead. */
            readonly created_by: components["schemas"]["UserSummary"];
            /** @description The user currently assigned to the lead. */
            readonly assigned_to: components["schemas"]["UserSummary"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Serializer used for retrieving lead activities. */
        LeadActivity: {
            readonly id: number;
            /** @description The user who performed the activity. */
            readonly user: components["schemas"]["UserSummary"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly activity_type: components["schemas"]["ActivityTypeEnum"];
            readonly description: string;
            readonly lead: number;
        };
        /** @description Validate the fields accepted when creating a lead. */
        LeadCreateRequest: {
            first_name: string;
            last_name: string;
            /** Format: email */
            email: string;
            phone?: string;
            company?: string;
            source?: string;
        };
        /** @description Serializer used for retrieving lead notes. */
        LeadNote: {
            readonly id: number;
            lead: number;
            content: string;
            /** @description The user who created the note. */
            readonly author: components["schemas"]["UserSummary"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description Serializer used when creating a lead note. */
        LeadNoteCreateRequest: {
            content: string;
        };
        /** @description Serializer used for retrieving lead notes. */
        LeadNoteRequest: {
            lead: number;
            content: string;
        };
        /** @description Validate the fields accepted when updating a lead. */
        LeadUpdateRequest: {
            first_name: string;
            last_name: string;
            /** Format: email */
            email: string;
            phone?: string;
            company?: string;
            source?: string;
        };
        /** @description Validate credentials submitted for authentication. */
        LoginRequestRequest: {
            /**
             * Format: email
             * @description Registered email address.
             */
            email: string;
            /** @description User password. */
            password: string;
        };
        /** @description Validate a refresh token for invalidation. */
        LogoutRequest: {
            /** @description Refresh token to invalidate. */
            refresh: string;
        };
        PaginatedLeadActivityList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["LeadActivity"][];
        };
        PaginatedLeadList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Lead"][];
        };
        PaginatedLeadNoteList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["LeadNote"][];
        };
        PaginatedUserSummaryList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["UserSummary"][];
        };
        /** @description Serializer used when updating a lead note. */
        PatchedLeadNoteUpdateRequest: {
            content?: string;
        };
        /** @description Validate the fields accepted when updating a lead. */
        PatchedLeadUpdateRequest: {
            first_name?: string;
            last_name?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            company?: string;
            source?: string;
        };
        /**
         * @description * `NEW` - New
         *     * `CONTACTED` - Contacted
         *     * `QUALIFIED` - Qualified
         *     * `PROPOSAL` - Proposal
         *     * `WON` - Won
         *     * `LOST` - Lost
         * @enum {string}
         */
        StatusEnum: "NEW" | "CONTACTED" | "QUALIFIED" | "PROPOSAL" | "WON" | "LOST";
        /** @description Serialize JWT access and refresh tokens. */
        Token: {
            /** @description JWT access token. */
            access: string;
            /** @description JWT refresh token. */
            refresh: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        /** @description Serialize read-only user account details. */
        User: {
            /** @description Unique user identifier. */
            readonly id: number;
            /**
             * Format: email
             * @description Registered email address.
             */
            readonly email: string;
            /** @description User's first name. */
            readonly first_name: string;
            /** @description User's last name. */
            readonly last_name: string;
            /** @description Assigned user role. */
            readonly role: string;
        };
        /** @description Serialize a lightweight representation of a user. */
        UserSummary: {
            readonly id: number;
            /** @description User's full name. */
            readonly full_name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequestRequest"];
                "multipart/form-data": components["schemas"]["LoginRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description The request could not be processed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LogoutRequest"];
                "multipart/form-data": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description No response body */
            205: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request could not be processed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefreshRequest"];
                "multipart/form-data": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    auth_users_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUserSummaryList"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    leads_list: {
        parameters: {
            query?: {
                /** @description Filter by assigned member. */
                assigned_to?: number;
                company?: string;
                /** @description Filter by creator. */
                created_by?: number;
                /** @description Order by created_at, updated_at, first_name, last_name or status. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description Search by first name, last name, email, phone or company. */
                search?: string;
                /** @description Filter by lead source. */
                source?: string;
                /** @description Filter by lead status. */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLeadList"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    leads_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LeadCreateRequest"];
                "multipart/form-data": components["schemas"]["LeadCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lead"];
                };
            };
            /** @description The request could not be processed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    leads_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this lead. */
                id: number;
                /** @description Unique lead identifier. */
                pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lead"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description You do not have permission to perform this action. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Requested resource was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    leads_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this lead. */
                id: number;
                /** @description Unique lead identifier. */
                pk: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LeadUpdateRequest"];
                "multipart/form-data": components["schemas"]["LeadUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lead"];
                };
            };
            /** @description The request could not be processed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description You do not have permission to perform this action. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Requested resource was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    leads_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this lead. */
                id: number;
                /** @description Unique lead identifier. */
                pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lead deleted successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description You do not have permission to perform this action. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Requested resource was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    leads_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this lead. */
                id: number;
                /** @description Unique lead identifier. */
                pk: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedLeadUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedLeadUpdateRequest"];
                "multipart/form-data": components["schemas"]["PatchedLeadUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lead"];
                };
            };
            /** @description The request could not be processed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description You do not have permission to perform this action. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Requested resource was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    leads_activities_list: {
        parameters: {
            query?: {
                assigned_to?: number;
                company?: string;
                created_by?: number;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
                /**
                 * @description * `NEW` - New
                 *     * `CONTACTED` - Contacted
                 *     * `QUALIFIED` - Qualified
                 *     * `PROPOSAL` - Proposal
                 *     * `WON` - Won
                 *     * `LOST` - Lost
                 */
                status?: "CONTACTED" | "LOST" | "NEW" | "PROPOSAL" | "QUALIFIED" | "WON";
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this lead. */
                id: number;
                /** @description Unique lead identifier. */
                pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLeadActivityList"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description You do not have permission to perform this action. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Requested resource was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    leads_assign_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this lead. */
                id: number;
                /** @description Unique lead identifier. */
                pk: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignLeadRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AssignLeadRequest"];
                "multipart/form-data": components["schemas"]["AssignLeadRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lead"];
                };
            };
            /** @description The request could not be processed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description You do not have permission to perform this action. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Requested resource was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    leads_notes_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this lead. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadNoteCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LeadNoteCreateRequest"];
                "multipart/form-data": components["schemas"]["LeadNoteCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadNote"];
                };
            };
            /** @description The request could not be processed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description You do not have permission to perform this action. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Requested resource was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    leads_notes_list_list: {
        parameters: {
            query?: {
                assigned_to?: number;
                company?: string;
                created_by?: number;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                /** @description A search term. */
                search?: string;
                /**
                 * @description * `NEW` - New
                 *     * `CONTACTED` - Contacted
                 *     * `QUALIFIED` - Qualified
                 *     * `PROPOSAL` - Proposal
                 *     * `WON` - Won
                 *     * `LOST` - Lost
                 */
                status?: "CONTACTED" | "LOST" | "NEW" | "PROPOSAL" | "QUALIFIED" | "WON";
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this lead. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedLeadNoteList"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description You do not have permission to perform this action. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Requested resource was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    leads_status_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this lead. */
                id: number;
                /** @description Unique lead identifier. */
                pk: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeLeadStatusRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ChangeLeadStatusRequest"];
                "multipart/form-data": components["schemas"]["ChangeLeadStatusRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lead"];
                };
            };
            /** @description The request could not be processed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description You do not have permission to perform this action. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Requested resource was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    leads_notes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this lead note. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadNoteRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LeadNoteRequest"];
                "multipart/form-data": components["schemas"]["LeadNoteRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadNote"];
                };
            };
        };
    };
    deleteLeadNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this lead note. */
                id: number;
                /** @description Unique note identifier. */
                pk: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lead note deleted successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description You do not have permission to perform this action. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Requested resource was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateLeadNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this lead note. */
                id: number;
                /** @description Unique note identifier. */
                note_pk: number;
                /** @description Unique lead identifier. */
                pk: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedLeadNoteUpdateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedLeadNoteUpdateRequest"];
                "multipart/form-data": components["schemas"]["PatchedLeadNoteUpdateRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadNote"];
                };
            };
            /** @description The request could not be processed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Authentication credentials are invalid or missing. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description You do not have permission to perform this action. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Requested resource was not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    leads_public_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LeadCreateRequest"];
                "multipart/form-data": components["schemas"]["LeadCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lead"];
                };
            };
        };
    };
}
