# Generated by Django 6.0.7 on 2026-07-25 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_leadactivity_leadnote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadactivity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead Activity', 'verbose_name_plural': 'Lead Activities'},
        ),
    ]
